#!/usr/bin/env bash
#RSA Factoring Challenge

factcheck()
{
	if [ $# -ne 3 ];
	then
		args=("$@")
		c=0
		n2=1

		for a in ${args[*]};
		do
			if [ $c -gt 1 ];
			then

				n2=$(echo $a*$n2 | bc)

			fi
				c=$((c + 1))
		done
	else
		n2=$3
	fi
	n1=$2
	n=$(echo "$1" | tr ':' '=')
	out=$(echo "if($n2 > $n1) 1 else 0" | bc)

	if ((out == 1)); then
		ncp=$n1
		n1=$n2
		n2=$ncp
	fi
	echo "$n$n1*$n2"
}

if [ $# -ne 1 ]
then

	echo 'Usage: rsa <file>'
	exit 1

else
	while read i

	do
		out=$(factor "$i")
		factcheck $out

	done < "$1"
fi
